[build.environment]
  # Disable Netlify's built-in npm install behaviour:
  NPM_FLAGS="--version"

[build]
  # Build the project using pnpm
  command = "npx pnpm@6.32.3 install --store-dir=.pnpm --frozen-lockfile && npx pnpm@6.32.3 build:all"




