packages:
  # the root package.json
  - '.'
  # all packages in subdirs of packages/ and components/
  - 'packages/**/*'
  # all packages in subdirs of config/
  - 'config/**/*'
  # exclude packages that are inside test/ directories
  - '!**/test/**'